routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('{any}', 'Panel\PanelController@index')->where('any', '.*');
//Route::get('/{route?}', 'RouteController@show')->where('route', '([0-9]+(\/){0,1})*');
//Route::get('{vue_capture?}', 'Panel\PanelController@index')->where('vue_capture', '[\/\w\.-]*');

Route::get('/', function () { return view('welcome'); });
Route::get('about', function () { return view('welcome'); });
Route::get('access', 'Panel\PanelController@login')->name('login');
Route::post('access', 'Panel\PanelController@loginCheck')->name('loginCheck');
Route::get('access-recovery', 'Panel\PanelController@forgetPassword')->name('forgetPassword');
Route::post('access-recovery', 'Panel\PanelController@passwordRecovery')->name('forgetPassword');
Route::get('logout', 'Panel\PanelController@logout')->name('logout');
Route::get('lan/{code}', 'Panel\PanelController@switchLanguage')->name('lan');

Route::prefix('panel')->middleware('staff')->group(function (){
    Route::get('/', 'Panel\PanelController@index')->name('panel-dashboard');
    Route::get('shop', 'Panel\PanelController@ecommerce')->name('panel-shop');
    Route::resource('product', 'Panel\ProductController')->names('product');

    Route::prefix('setting')->group(function (){
        Route::get('/', 'Panel\PanelController@index')->name('setting');
        Route::resource('category', 'Panel\CategoryController')->names('category');
        Route::resource('brand', 'Panel\BrandController')->names('brand');
        Route::resource('unit', 'Panel\UnitController')->names('unit');
        Route::resource('staff', 'Panel\StaffController')->names('staff');
        Route::get('staff/{code}/status-change', 'Panel\StaffController@changeStatus')->name('staff.changeStatus');
        Route::resource('rule', 'Panel\StaffRuleController')->names('staff-rule');
        Route::get('rule/{code}/assigned', 'Panel\StaffRuleController@assigned')->name('staff-rule.assigned');
        Route::resource('supplier', 'Panel\SupplierController')->names('supplier');
        Route::resource('warehouse', 'Panel\WarehouseController')->names('warehouse');
        Route::resource('price-group', 'Panel\PriceGroupController')->names('priceGroup');
        Route::resource('customer', 'Panel\CustomerController')->names('customer');
        Route::resource('bank', 'Panel\BankController')->names('bank');
    });
});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Panel/BankController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Bank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BankController extends Controller
{
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        //
    }
}

app/Http/Controllers/Panel/BrandController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Brand;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class BrandController extends Controller
{
    public function index()
    {
        $title = "Brand List";
        $brands = Brand::all();
        return view('Panel.Default.BrandList', compact('title', 'brands'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $request->validate([

        ]);

        $data['code'] = uniqid();
        $data['name'] = $request->name;
        $data['slug'] = $request->slug?Str::slug($request->slug):Str::slug($request->name);
        $data['details'] = $request->description;
        $data['logo'] = $request->logo;
        if($request->image){
            $data['logo'] = $data['code'].".".$request->file('image')->getClientOriginalExtension();
        }

        try{
            Brand::create($data);
        } catch (\PDOException $e){
            Session::put('message.error', $e);
            return back();
        }

        if ($request->image){
            Storage::disk('public')->putFileAs('Brand', $request->file('image'), $data['logo']);
        }
        Session::put('message.success', "New Brand added successfully.");
        return back();
    }

    public function show(Brand $brand)
    {
        //
    }

    public function edit(Brand $brand)
    {
        //
    }

    public function update(Request $request, Brand $brand)
    {
        //
    }

    public function destroy($code)
    {
        $brand = Brand::where('code', $code)->first();
        if ($brand){
            try{
                $brand->delete();
            } catch (\PDOException $e){
                Session::put('message.error', $e);
                return back();
            }
            if ($brand->logo){
                Storage::disk('public')->delete('Brand/'.$brand->logo);
            }
            Session::put('message.success', "Brand delete successfully.");
            return back();
        } else {
            Session::put('message.error', "This brand is not available. Please reload and try again.");
            return back();
        }
    }
}

app/Http/Controllers/Panel/CategoryController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{

    public function index()
    {
        $title = "Category";
        $categories = Category::all();
        return view('Panel.Default.PriceGroup', compact('title', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        //
    }
}

app/Http/Controllers/Panel/CustomerController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Customer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        //
    }
}

app/Http/Controllers/Panel/GroupPriceController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\GroupPrice;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupPriceController extends Controller
{
    public function index()
    {
        //
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        //
    }

    public function show(GroupPrice $groupPrice)
    {
        //
    }

    public function edit(GroupPrice $groupPrice)
    {
        //
    }

    public function update(Request $request, GroupPrice $groupPrice)
    {
        //
    }

    public function destroy(GroupPrice $groupPrice)
    {
        //
    }
}

app/Http/Controllers/Panel/PanelController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Staff;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class PanelController extends Controller
{
    public $backPage;

    public function index()
    {
        $title = 'Dashboard';
        return view('Panel.Default.PanelHome', compact('title'));
    }

    public function dashboard()
    {
        return "Hello Dashboard";
    }

    public function ecommerce()
    {
        $title = 'E-Commerce';
        return view('Panel.Default.Ecommerce', compact('title'));
    }

    public function login(){
        $this->backPage = url()->previous();
        if (Auth::guard('staff')->check()){
            return back();
        } else {
            return view('Panel.Default.Login');
        }
    }

    public function loginCheck(Request $request){
        $request->validate([
            'username' => 'required',
            'password' => 'required',
        ]);

//        dd(Auth::guard('staff')->id);
        $staff = Staff::where('username', $request->username)->orWhere('email', $request->username)->orWhere('phone', $request->username)->first();
        if (!null == $staff && ($staff->username == $request->username | $staff->email == $request->username | $staff->phone == $request->username)) {
           if (Hash::check($request->password, $staff->password)) {
                if ($staff->active == 1 && $staff->role != 10) {
                    $remember = $request->remember;
                    Auth::guard('staff')->attempt([
                        'username' => $request->username,
                        'password' => $request->password
                    ], $remember);
                    Session::put(['message.success' => "Login Successful"]);
                } elseif ($staff->role == 0) {
                    Session::put(['message.error' => 'Your panel access downgraded.']);
                    return back()->withInput();
                } else {
                    Session::put(['message.error' => "User is inactive."]);
                    return back()->withInput();
                }
            } else {
                Session::put(['message.error' => "Password not matching. Input carefully"]);
                return back()->withInput();
            }
        } else {
            Session::put(['message.error' => "Username not matching."]);
            return back()->withInput();
        }
        if (isset($this->backPage) && !null == $this->backPage) {
            return redirect($this->backPage);
        } else {
            return redirect(route('panel-dashboard'));
        }


    }

    public function forgetPassword (){
        dd("Forget password form");
    }

    public function switchLanguage($code){
        Session::put('lang', $code);
        App::getLocale();
        return back();
    }

    public function passwordRecovery(Request $request){
        dd($request->all());
    }

    public function logout(){
        Auth::guard('staff')->logout();
        Session::flush();
        return redirect('/');
    }
}

app/Http/Controllers/Panel/PriceGroupController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\PriceGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Session;

class PriceGroupController extends Controller
{
    public function index()
    {
        $title = "Price Group";
        $priceGroups = PriceGroup::all();
        return view('Panel.Default.PriceGroup', compact('title', 'priceGroups'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        if (!null == $request->name && $request->name != ""){
            try{
                PriceGroup::create(['code' => uniqid(), 'name' => $request->name]);
            } catch (\PDOException $e){
                Session::put(['message.error' => $e->getMessage()]);
                return back()->withInput();
            }
            Session::put(['message.success', 'New Price Group add successful.']);
            return back();
        } else {
            Session::put(['message.warning', 'Name can not be empty. Fill-up carefully']);
            return back()->withInput();
        }
    }

    public function show(PriceGroup $priceGroup)
    {
        //
    }

    public function edit(PriceGroup $priceGroup)
    {
        //
    }

    public function update(Request $request, PriceGroup $priceGroup)
    {
        //
    }

    public function destroy(Request $request)
    {
        dd($request);
    }
}

app/Http/Controllers/Panel/ProductController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{

    public function index()
    {
        //
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //
    }


    public function show(Product $product)
    {
        //
    }

    public function edit(Product $product)
    {
        //
    }


    public function update(Request $request, Product $product)
    {
        //
    }


    public function destroy(Product $product)
    {
        //
    }
}

app/Http/Controllers/Panel/UnitController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Model\Unit;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UnitController extends Controller
{

    public function index()
    {
        //
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //
    }


    public function show(Unit $unit)
    {
        //
    }


    public function edit(Unit $unit)
    {
        //
    }


    public function update(Request $request, Unit $unit)
    {
        //
    }


    public function destroy(Unit $unit)
    {
        //
    }
}

resources/views/Panel/Default/BrandList.blade.php
@extends('Master.Panel')

@section('style')
    <style type="text/css">
        .form-group {
            margin-bottom: 9px;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{{ asset('/Default/app-assets/css/plugins/forms/validation/form-validation.css') }}">
@stop
@section('body')
{{--    @php($topic = ['title' => 'Staff rule', 'breadcrumb' => ['Dashboard' => route('panel-dashboard'), 'Setting' => route('staff-rule.index'), 'staff-rule' => null], 'menu' => ['Add new' => 'addnew', 'Edit' => '', 'Delete' => '']])--}}
{{--    @include('Elements.TopicHeader', ['data' => $topic])--}}

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="mb-0">Brand List</h4>
                    <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
                            <div class="dropdown">
                                <button class="btn-icon btn btn-outline-primary btn-round btn-sm dropdown-toggle waves-effect waves-light" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="feather icon-settings"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-right">
{{--                                    <a href="{{ route('staff-rule.index') }}" class="dropdown-item"><i class="feather icon-plus"></i>Staff rule list</a>--}}
                                    <a class="dropdown-item" id="create"><i class="feather icon-plus"></i>Add New Brand</a>
                                    <a class="dropdown-item" href="#"><i class="feather icon-trash-2"></i>Delete</a>
                                </div>
                            </div>
                    </div>
                </div>
                <div class="card-content listView">
                    <div class="table-responsive mt-1">
                        <table class="table table-hover-animation mb-0">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>LOGO</th>
                                <th>NAME</th>
                                <th>CODE</th>
                                <th>SLUG</th>
                                <th class="form-actions right">ACTION</th>
                            </tr>
                            </thead>
                            <tbody id="staff_rule_table">
                            @php($x = 1)
                            @foreach ($brands as $brand)
                                <tr>
                                    <td>{{ $x++ }}</td>
                                    <td>
                                        <div class="avatar mr-1 ">
                                            @if ($brand->logo)
                                                <img src="{{ asset('/storage/Brand/'.$brand->logo) }}" alt="avtar img holder" height="32" width="32">
                                            @else
                                                <span class="avatar-content">{{ explode(' ', $brand->name)[0] }}</span>
                                            @endif
                                        </div>
                                    </td>
                                    <td>{{ $brand->name }}</td>
                                    <td>{{ $brand->code }}</td>
                                    <td>{{ $brand->slug }}</td>

{{--    TODO need to change button link as staff list page button link--}}

                                    <td class="form-actions right">
{{--                                        <a href="{{ route('staff.assigned', $brand->code) }}" class="btn btn-sm btn-icon rounded-circle btn-outline-dark waves-effect waves-light" data-toggle="tooltip" data-placement="top" data-original-title="Staff List">--}}
{{--                                            <i class="ficon feather icon-users"></i></a>--}}
                                        <a href="{{ route('brand.show', $brand->code) }}" class="btn btn-sm btn-icon rounded-circle btn-outline-primary waves-effect waves-light" data-toggle="tooltip" data-placement="top" title="Brand Products" data-original-title="Profile">
                                            <i class="ficon feather icon-clipboard"></i></a>
                                        <a href="{{ route('brand.edit', $brand->code) }}"  class="btn btn-sm btn-icon rounded-circle btn-outline-warning waves-effect waves-light" data-value="{{ route('api.warehouse.info', $brand->code) }}" data-toggle="tooltip" data-placement="top" title="Edit" data-original-title="Chat">
                                            <i class="ficon feather icon-edit"></i></a>
                                        {!! Form::open(['route' => ['brand.destroy', $brand->code], 'method' => 'delete', 'style' => 'display:inline']) !!}
                                        {{ Form::button('<i class="ficon feather icon-trash"></i></a>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon rounded-circle btn-outline-danger waves-effect waves-light', 'data-toggle' => "tooltip", 'data-placement' => "top", 'data-original-title' => "Delete"]) }}
                                        {!! Form::close() !!}

                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="card-content create" style="display: none">
                    <div class="card-body">
                        {{ Form::open(['route' => 'brand.store', 'method' => 'post', 'class' => 'form form-horizontal validate', 'files' => true, 'novalidate']) }}
                        <div class="form-body">
                            <div class="divider">
                                <div class="divider-text">Brand Information</div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 col-12">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <span>{{ Form::label('name', 'Name') }}</span>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group position-relative has-icon-left input-divider-left">
                                                {{ Form::text('name', null, ['id' => 'name', 'class' => 'form-control round', 'placeholder' => 'Brand name', 'autofocus', 'required']) }}
                                                <div class="form-control-position">
                                                    <i class="feather icon-cpu"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <span>{{ Form::label('slug', 'Slug') }}</span>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group position-relative has-icon-left input-divider-left">
                                                {{ Form::text('slug', null, ['id' => 'slug', 'class' => 'form-control round', 'placeholder' => 'Input slug']) }}
                                                <div class="form-control-position">
                                                    <i class="feather icon-link"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <span>{{ Form::label('description', 'Description') }}</span>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group position-relative has-icon-left input-divider-left">
                                                {{ Form::tel('description', null, ['id' => 'description', 'class' => 'form-control round', 'placeholder' => 'Input description']) }}
                                                <div class="form-control-position">
                                                    <i class="feather icon-file-plus"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-12">
                                    <div class="form-group row">
                                        <div class="col-md-4">
                                            <span>{{ Form::label('image', 'Logo') }}</span>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group position-relative has-icon-left input-divider-left">
                                                {{ Form::file('image', ['id' => 'image', 'class' => 'form-control round', 'placeholder' => 'Upload Logo', 'accept' => '.png, .gif']) }}
                                                <div class="form-control-position">
                                                    <i class="feather icon-image"></i>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="divider">
                                <div class="divider-text"></div>
                            </div>
                            <div class="row">
                                <div class="col-12 text-center">
                                    {!! Form::button('Submit', ['type' => 'submit', 'class' => 'btn btn-primary mr-1 mb-1 waves-effect waves-light']) !!}
                                    {!! Form::button('Reset', ['type' => 'reset', 'class' => 'btn btn-outline-warning mr-1 mb-1 waves-effect waves-light']) !!}
                                    {!! Form::button('Cancel', ['id' => 'cancel', 'class' => 'btn btn-warning mr-1 mb-1 waves-effect waves-light']) !!}
                                </div>
                            </div>
                        </div>
                        {{ Form::close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function () {
            $("#create").click(function(){
                $(".create").show("slow");
                $(".listView").hide("slow");
                $(".card-header h4").html("Add new Brand")
            });
            $("#cancel").click(function(){
                $(".create").hide("slow");
                $(".listView").show("slow");
                $(".card-header h4").html("Brand List")
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".change-status-active").mouseover(function () {
                $(this).children("i").removeClass('icon-check-circle').addClass('icon-refresh-cw');
            }).mouseout(function () {
                $(this).children("i").addClass('icon-check-circle').removeClass('icon-refresh-cw');
            });
            $(".change-status-inactive").mouseover(function () {
                $(this).children("i").addClass('icon-refresh-cw').removeClass('icon-x-circle');
            }).mouseout(function () {
                $(this).children("i").addClass('icon-x-circle').removeClass('icon-refresh-cw');
            })
        })
    </script>

    <script src="{{ asset('Default/app-assets/vendors/js/forms/validation/jqBootstrapValidation.js') }}"></script>
    <script src="{{ asset('Default/app-assets/js/scripts/forms/validation/form-validation.js') }}"></script>
    <script src="{{ asset('Default/app-assets/vendors/js/pickers/pickadate/picker.js') }}"></script>
    <script src="{{ asset('Default/app-assets/vendors/js/pickers/pickadate/picker.date.js') }}"></script>
    <script src="{{ asset('Default/app-assets/js/scripts/pickers/dateTime/pick-a-datetime.js') }}"></script>
@stop