routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('{any}', 'Panel\PanelController@index')->where('any', '.*');
//Route::get('/{route?}', 'RouteController@show')->where('route', '([0-9]+(\/){0,1})*');
//Route::get('{vue_capture?}', 'Panel\PanelController@index')->where('vue_capture', '[\/\w\.-]*');

Route::get('/', function () { return view('welcome'); });
Route::get('about', function () { return view('welcome'); });
Route::get('access', 'Panel\PanelController@login')->name('login');
Route::post('access', 'Panel\PanelController@loginCheck')->name('loginCheck');
Route::get('access-recovery', 'Panel\PanelController@forgetPassword')->name('forgetPassword');
Route::post('access-recovery', 'Panel\PanelController@passwordRecovery')->name('forgetPassword');
Route::get('logout', 'Panel\PanelController@logout')->name('logout');
Route::get('lan/{code}', 'Panel\PanelController@switchLanguage')->name('lan');

Route::prefix('panel')->middleware('staff')->group(function (){
    Route::get('/', 'Panel\PanelController@index')->name('panel-dashboard');
    Route::get('shop', 'Panel\PanelController@ecommerce')->name('panel-shop');
    Route::resource('product', 'Panel\ProductController')->names('product');

    Route::prefix('setting')->group(function (){
        Route::get('/', 'Panel\PanelController@index')->name('setting');
        Route::resource('category', 'Panel\CategoryController')->names('category');
        Route::resource('brand', 'Panel\BrandController')->names('brand');
        Route::resource('unit', 'Panel\UnitController')->names('unit');
        Route::resource('staff', 'Panel\StaffController')->names('staff');
        Route::get('staff/{code}/status-change', 'Panel\StaffController@changeStatus')->name('staff.changeStatus');
        Route::resource('rule', 'Panel\StaffRuleController')->names('staff-rule');
        Route::get('rule/{code}/assigned', 'Panel\StaffRuleController@assigned')->name('staff-rule.assigned');
        Route::resource('supplier', 'Panel\SupplierController')->names('supplier');
        Route::resource('warehouse', 'Panel\WarehouseController')->names('warehouse');
        Route::resource('price-group', 'Panel\PriceGroupController')->names('priceGroup');
        Route::resource('customer', 'Panel\CustomerController')->names('customer');
        Route::resource('bank', 'Panel\BankController')->names('bank');
    });
});

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/Elements/Customizer.blade.php
<div class="customizer d-none d-md-block"><a class="customizer-close"
                                             href="#"><i
            class="feather icon-x"></i></a><a class="customizer-toggle"
                                              href="#"><i
            class="feather icon-settings fa fa-spin fa-fw white"></i></a>
    <div class="customizer-content p-2 ps ps--active-y">
        <h4 class="text-uppercase mb-0">Theme Customizer</h4>
        <small>Customize &amp; Preview in Real Time</small>
        <hr>
        <!-- Menu Colors Starts -->
        <div id="customizer-theme-colors">
            <h5>Menu Colors</h5>
            <ul class="list-inline unstyled-list">
                <li class="color-box bg-primary selected" data-color="theme-primary"></li>
                <li class="color-box bg-success" data-color="theme-success"></li>
                <li class="color-box bg-danger" data-color="theme-danger"></li>
                <li class="color-box bg-info" data-color="theme-info"></li>
                <li class="color-box bg-warning" data-color="theme-warning"></li>
                <li class="color-box bg-dark" data-color="theme-dark"></li>
            </ul>
        </div>
        <!-- Menu Colors Ends -->
        <hr>
        <!-- Theme options starts -->
        <h5 class="mt-1">Theme Layout</h5>
        <div class="theme-layouts">
            <div class="d-flex justify-content-start">
                <div class="mx-50">
                    <fieldset>
                        <div class="vs-radio-con vs-radio-primary">
                            <input type="radio" name="layoutOptions" value="false" class="layout-name"
                                   data-layout=""
                                   checked="">
                            <span class="vs-radio">
              <span class="vs-radio--border"></span>
              <span class="vs-radio--circle"></span>
            </span>
                            <span class="">Light</span>
                        </div>
                    </fieldset>
                </div>
                <div class="mx-50">
                    <fieldset>
                        <div class="vs-radio-con vs-radio-primary">
                            <input type="radio" name="layoutOptions" value="false" class="layout-name"
                                   data-layout="dark-layout">
                            <span class="vs-radio">
              <span class="vs-radio--border"></span>
              <span class="vs-radio--circle"></span>
            </span>
                            <span class="">Dark</span>
                        </div>
                    </fieldset>
                </div>
                <div class="mx-50">
                    <fieldset>
                        <div class="vs-radio-con vs-radio-primary">
                            <input type="radio" name="layoutOptions" value="false" class="layout-name"
                                   data-layout="semi-dark-layout">
                            <span class="vs-radio">
              <span class="vs-radio--border"></span>
              <span class="vs-radio--circle"></span>
            </span>
                            <span class="">Semi Dark</span>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
        <!-- Theme options starts -->
        <hr>

        <!-- Collapse sidebar switch starts -->
        <div class="collapse-sidebar d-flex justify-content-between">
            <div class="collapse-option-title">
                <h5 class="pt-25">Collapse Sidebar</h5>
            </div>
            <div class="collapse-option-switch">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="collapse-sidebar-switch">
                    <label class="custom-control-label" for="collapse-sidebar-switch"></label>
                </div>
            </div>
        </div>
        <!-- Collapse sidebar switch Ends -->
        <hr>

        <!-- Navbar colors starts -->
        <div id="customizer-navbar-colors">
            <h5>Navbar Colors</h5>
            <ul class="list-inline unstyled-list">
                <li class="color-box bg-white border selected" data-navbar-default=""></li>
                <li class="color-box bg-primary" data-navbar-color="bg-primary"></li>
                <li class="color-box bg-success" data-navbar-color="bg-success"></li>
                <li class="color-box bg-danger" data-navbar-color="bg-danger"></li>
                <li class="color-box bg-info" data-navbar-color="bg-info"></li>
                <li class="color-box bg-warning" data-navbar-color="bg-warning"></li>
                <li class="color-box bg-dark" data-navbar-color="bg-dark"></li>
            </ul>
        </div>
        <!-- Navbar colors starts -->
        <hr>
        <!-- Navbar Type Starts -->
        <h5>Navbar Type</h5>
        <div class="navbar-type d-flex justify-content-between">
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="navbarType" value="false" id="navbar-hidden">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Hidden</span>
                    </div>
                </fieldset>
            </div>
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="navbarType" value="false" id="navbar-static">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Static</span>
                    </div>
                </fieldset>
            </div>
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="navbarType" value="false" id="navbar-sticky">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Sticky</span>
                    </div>
                </fieldset>
            </div>
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="navbarType" value="false" id="navbar-floating" checked="">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Floating</span>
                    </div>
                </fieldset>
            </div>
        </div>
        <!-- Navbar Type Starts -->
        <hr>

        <!-- Footer Type Starts -->
        <h5>Footer Type</h5>
        <div class="footer-type d-flex justify-content-start">
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="footerType" value="false" id="footer-hidden">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Hidden</span>
                    </div>
                </fieldset>
            </div>
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="footerType" value="false" id="footer-static" checked="">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Static</span>
                    </div>
                </fieldset>
            </div>
            <div class="mx-50">
                <fieldset>
                    <div class="vs-radio-con vs-radio-primary">
                        <input type="radio" name="footerType" value="false" id="footer-sticky">
                        <span class="vs-radio">
            <span class="vs-radio--border"></span>
            <span class="vs-radio--circle"></span>
          </span>
                        <span class="">Sticky</span>
                    </div>
                </fieldset>
            </div>
        </div>
        <!-- Footer Type Ends -->
        <hr>

        <!-- Hide Scroll To Top Starts-->
        <div class="hide-scroll-to-top d-flex justify-content-between py-25">
            <div class="hide-scroll-title">
                <h5 class="pt-25">Hide Scroll To Top</h5>
            </div>
            <div class="hide-scroll-top-switch">
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="hide-scroll-top-switch">
                    <label class="custom-control-label" for="hide-scroll-top-switch"></label>
                </div>
            </div>
        </div>
        <!-- Hide Scroll To Top Ends-->
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;">
            <div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div>
        </div>
        <div class="ps__rail-y" style="top: 0px; height: 606px; right: 0px;">
            <div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 505px;"></div>
        </div>
    </div>

</div>

resources/views/Elements/FootButton.blade.php
<div class="buy-now"><a target="_blank" class="btn btn-white waves-effect waves-light">{{ $data }}</a></div>

resources/views/Elements/Footer.blade.php
<footer class="footer footer-static footer-light">
    <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">COPYRIGHT  © {{ date("Y") }}<a
                class="text-bold-800 grey darken-2"
                href="http://alam.foxof.org" target="_blank">{{ config('app.name') }}</a>All rights Reserved</span><span
            class="float-md-right d-none d-md-block"><span class="foot" title="Khorshed Alam">K</span>
            <span class="foot" title="Al Hasan">A</span>
            <span class="foot" title="Jibon Chandra Roy">J</span>
            <span class="foot" title="Touhidul Islam">T</span> &amp; Made with<i
                class="feather icon-heart pink"></i></span>
        <button class="btn btn-primary btn-icon scroll-top waves-effect waves-light" type="button"><i
                class="feather icon-arrow-up"></i></button>
    </p>
    <style type="text/css">
        .foot {
            border-radius: 25%;
            cursor: default;
            border: 1px solid #EA5455;
            padding: 0 3px;
        }
    </style>
</footer>

resources/views/Elements/TopicHeader.blade.php
<div class="content-header row">
    <div class="content-header-left col-md-9 col-12 mb-2">
        <div class="row breadcrumbs-top">
            <div class="col-12">
                @if (isset($data['title']) && !null == $data['title'])
                    <h2 class="content-header-title float-left mb-0">{{ $data['title'] }}</h2>
                @endif
                @if (isset($data['breadcrumb']) && !null == $data['breadcrumb'])
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                @foreach($data['breadcrumb'] as $step => $stepLink)
                                    <li class="breadcrumb-item">
                                        @if ($stepLink)
                                            <a href="{{ $stepLink }}">{{ $step }}</a>
                                        @else
                                            {{ $step }}
                                        @endif
                                    </li>
                                @endforeach
                            </ol>
                        </div>
                @endif
            </div>
        </div>
    </div>
    @if (isset($data['menu']) && !null == $data['menu'])
        <div class="content-header-right text-md-right col-md-3 col-12 d-md-block d-none">
            <div class="form-group breadcrum-right">
                <div class="dropdown">
                    <button class="btn-icon btn btn-primary btn-round btn-sm dropdown-toggle waves-effect waves-light"
                            type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
                            class="feather icon-settings"></i></button>
                    <div class="dropdown-menu dropdown-menu-right" x-placement="top-end">
                        @foreach($data['menu'] as $menu => $menuLink)
                            <a class="dropdown-item" href="{{ $menuLink }}">{{ $menu }}</a>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    @endif
</div>

{{--@php($topic = ['title' => 'Warehouse List', 'breadcrumb' => ['Dashboard' => route('panel-dashboard'), 'Setting' => route('warehouse.index'), 'Warehouse' => null], 'menu' => ['Add new' => 'addnew', 'Edit' => '', 'Delete' => '']])--}}